### ISSUE TITLE
Abandon support for python 2

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#119]
Python 2 will be officially deprecated as of Jan. 1, 2020.

https://www.python.org/dev/peps/pep-0373/

**Comment by kanderso-nrel** [comment]
Is this slated for the next RdTools release, meaning that new PRs don't need to worry about supporting 2.7?

**Comment by mdeceglie** [comment]
At this point, I support that.

**Comment by kanderso-nrel** [comment]
FYI README.md in the development branch currently says 2.7 is supported, may want to update before the major release.
