### ISSUE TITLE
clean up documentation and set up readthedocs

### ISSUE THREAD

**Issue by kevinsa5** [NREL/rdtools#122]
Sphinx is the main way to use RTD, but the default sphinx (or rather restructuredtext) docstring format is not necessarily very pretty.  The Google and NumPy docstring formats are supported through the napoleon sphinx extension (pvlib uses this): https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

Should this be done prior to (or as a part of) cutting the next big release?

**Comment by mikofski** [comment]
My vote is for numpy style docs

```
Parameters
----------
var1 : type
    description
var2 : type
    description
```

this is [the doc style used by pvlib](https://pvlib-python.readthedocs.io/en/latest/contributing.html#documentation)

**Comment by kanderso-nrel** [comment]
The real question is what Sphinx theme to use... http://www.sphinx-doc.org/en/master/usage/theming.html#builtin-themes

The RTD theme isn't built in but seems like the obvious choice.

**Comment by mdeceglie** [comment]
I vote for RTD!

**Comment by kanderso-nrel** [comment]
Closed by #125

**Comment by mdeceglie** [comment]
Let's keep this open until it ends up in `Master`. I'll tag it with "fixed in development branch" so we can keep tabs of changes for the new release.

**Comment by kanderso-nrel** [comment]
Oops, thanks.  Will keep that in mind.
