### ISSUE TITLE
Evaluate/comply with pv-terms

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#175]
Let's comply with pv-terms if possible: https://github.com/DuraMAT/pv-terms

**Comment by kanderso-nrel** [comment]
It sounds like the current set of terms is still preliminary and will change in the near future, but the direction pv-terms is going is to follow a "taxonomy" scheme roughly of the form `[measurement]_[characteristic]_[modifier]`, for example "voltage_ac_norm".  However, nailing down specifics like "voltage_ac_norm" or "v_ac_norm" is not yet done, so it's not quite time to start renaming things in RdTools yet.  Here is an incomplete set of changes that seem likely:
- `normalized_energy`, `normalized` -> `energy_norm` or `energy_normalized`
- `daily_normalized_energy` -> `energy_norm_daily` or `energy_daily_norm`
- `daily_insolation` -> `insolation_daily` (note: pv-terms currently doesn't define insolation terms, https://github.com/DuraMAT/pv-terms/issues/15)
- `poa`, `measured_poa` -> `poa_global`
- `clearsky_poa` -> `poa_global_clearsky` (?)
- `tcell`, `T_cell` -> `temperature_cell` or possible `t_cell`
- `gamma_pdc` -> `gamma_pmp`

**Comment by cdeline** [comment]
Merged into development.  Fixed by #185
