### ISSUE TITLE
Minor notebook to rst conversion issue on RTD

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#191]
A superscript footnote number loses the formatting when converting the source notebook to RST during the sphinx build:

https://rdtools.readthedocs.io/en/latest/example.html#5:-Soiling-calculations
![image](https://user-images.githubusercontent.com/57452607/90068959-c7a32700-dcae-11ea-9087-364ea2999198.png)

**Comment by kanderso-nrel** [comment]
One way forward is using restructured text references, which survive the notebook->html conversion process and end up rendering nicely.  This specific example renders a little strangely because the leading `M.` and `G.` are interpreted as nested list elements instead of part of the citation text. 

If we do use this feature, we should consider using it for all references across the documentation because they are global.

https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#citations

**Comment by mdeceglie** [comment]
Closed with #214
