### ISSUE TITLE
Supplement/replace clipping filter logic

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#192]
The clipping filter function [filtering.clip_filter](https://github.com/NREL/rdtools/blob/master/rdtools/filtering.py#L82-L102) is pretty simple and has been reported to give poor results in some circumstances (e.g. inverter derating from high ambient temp or in large systems with plant controllers that allow dynamic setpoints).  @matt14muller and @kperry2215 have developed an alternate method for the PV Fleets QA project to detect clipping through rolling differences and some other logic rather than a simple percentile threshold that could replace or sit alongside the current clipping filter.

**Comment by mdeceglie** [comment]
closed with #200  and #289
