### ISSUE TITLE
Travis config not fully consistent with setup.py

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#194]
Here are two proposed improvements to our [.travis.yml](https://github.com/NREL/rdtools/blob/development/.travis.yml).

---

First, Travis doesn't run `pip install rdtools[test]` during the job setup.  It's not currently a problem, I guess because Travis happens to supply the current requirements (like pytest) out of the box, so the tests pass.  But if we add a new requirement to `[test]` (for example, `tables` for #131), the requirements aren't met and the tests fail.  

I think changing these lines to `REQ_ENV='<...> .[test]'` will have the desired effect:
https://github.com/NREL/rdtools/blob/8f00cd4b75ba5f69cd4057496a21aeeb51e8607b/.travis.yml#L14-L16

---

Second, the minimum dependency versions specified in our setup.py aren't tested in the CI which makes it more likely for us to unintentionally break compatibility with the minimum supported versions.  I propose either: 1) changing requirements.txt to match our minimum supported versions, or 2) creating a `requirements-min.txt` with the minimum versions specified in setup.py and adding a third Travis `env` entry to use it for tests.  I'd prefer option 2 because `requirements.txt` is user-facing and I don't really think we should be encouraging people to use the oldest package versions possible.

**Comment by cdeline** [comment]
OK, I agree with this approach.  I'll create a feature branch to test these and merge into development to check.  I can merge back into modelchain pytests to see if it fixes things.

**Comment by cdeline** [comment]
Actually, on second thought I'm out of my depth here.  I'll leave it to you @kanderso-nrel, but I agree with this approach.

**Comment by mdeceglie** [comment]
Closed with #214
