### ISSUE TITLE
Deprecations in pvlib 0.8.0

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#198]
pvlib 0.8.0 (released 2020-09-08) deprecated the LocalizedPVSystem class, which is used by our SAPM-based normalization functions (e.g. [sapm_dc_power](https://rdtools.readthedocs.io/en/latest/generated/rdtools.normalization.sapm_dc_power.html)).  Note that we don't currently support the pvlib 0.8.x series, so technically this isn't an issue yet.  But it would be nice to solve it sooner rather than later.  Further context: https://github.com/pvlib/pvlib-python/pull/1034#issuecomment-684032830

Some ideas:
- Deprecate the SAPM functions in RdTools 2.0 and remove them in an eventual 3.0.
    - I have the notion that the SAPM-based normalization is not commonly-used.  People that still want to use it could have that function in their own code and use our `normalize_with_expected_power` function.
- Change the `pvlib_pvsystem` parameter to optionally be an (unlocalized) PVSystem object and add an optional `location` parameter.
    - I haven't prototyped this, but it seems like it would work, the function would just have to do a little bit of argument checking to figure out where it can find what it needs.
- Switch the parameter to be a pvlib ModelChain?
    - If we want to keep to the pattern of passing in a pvlib object to do an expected energy calculation, I suppose that's the way to do it.  But I'm not sure how much it helps the user to have us call `mc.run_model(...)` instead of them doing it and passing the result to `normalize_with_expected_power`.
- Something else?

I think the LocalizedPVSystem is the only deprecation that matters for us.  I ran the test suite on development with pvlib 0.8.0 installed and got no failures, only the deprecation warnings.

**Comment by mdeceglie** [comment]
Closed with #214
