### ISSUE TITLE
Improper clearsky interval labeling

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#243]
**Describe the bug**
Clear sky irradiance and sun position are calculated instantaneously but treated as right-labeled averages in the example notebooks and `TrendAnalysis` of #117 

**Expected behavior**
The most robust behavior would be to calculate at high frequency and aggregate.

**Comment by wholmgren** [comment]
Relevant thread on the pvlib python Google group: https://groups.google.com/d/msgid/pvlib-python/94230269-3421-4d50-a49c-79e46c3c815fn%40googlegroups.com

**Comment by martin-springer** [comment]
Closed with #281
