### ISSUE TITLE
Unit tests take too much memory.

### ISSUE THREAD

**Issue by abshinn** [NREL/rdtools#25]
I noticed that the unit tests take upwards of 15G of virtual memory. I don't understand why this would happen -- it would be useful to use a profiler the code to see what is going on.

**Comment by yjy1663** [comment]
I think the issue is cause by setting the index frequency to second which generate 90 millions data points during test.

~~~
        elif (input_freq == 'S'):
            x = pd.date_range(start='2012-01-01 00:00:00', end='2015-01-01 00:10:00', freq=input_freq)
            N = len(x)
            seconds = np.arange(N)
            y = np.ones(N) * np.power(1 + rd / (365 * 24 * 60 * 60), seconds)
            corr_energy = pd.Series(data=y, index=x)
~~~

**Comment by mdeceglie** [comment]
@yjy1663 Thanks for fixing this, it works well in my test. 

In the future, please make changes in a new branch and open a pull request before merging into master. For minor changes like this, the full cohort of reviews isn't necessary, but it is good practice to use the pull request and get someone else to put their eyes on the change. More info about workflow is available on the[ wiki](https://github.com/NREL/rdtools/wiki).
