### ISSUE TITLE
TrendAnalysis docstring refers to the filter_params attr as filter_parameters

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/rdtools#257]
`filter_parameters` is documented:
https://github.com/NREL/rdtools/blob/39993fc4e6b0d511001d97d8499953c05f4e448b/rdtools/analysis_chains.py#L63-L73

But the actual attribute name is `filter_params`:
https://github.com/NREL/rdtools/blob/39993fc4e6b0d511001d97d8499953c05f4e448b/rdtools/analysis_chains.py#L124-L131

I think the wrong name only exists in that one docstring section:
```
$ git grep filter_parameters
rdtools/analysis_chains.py:    filter_parameters: dict
rdtools/analysis_chains.py:        filter_parameters defaults to empty dicts for each function in rdtools.filtering,
```

The notebooks get it right, of course: https://rdtools.readthedocs.io/en/latest/TrendAnalysis_example.html#Modifying-the-filters

**Comment by mdeceglie** [comment]
closed with #289
