### ISSUE TITLE
different result using normalize_with_pvwatts, 0.18ver. vs. 0.17ver.

### ISSUE THREAD

**Issue by luciaxu2010** [NREL/rdtools#262]
**Describe the bug**
I got different normalized energy results using the normalize_with pvwatts between different version, could you kindly check?

**Full error message and traceback**
No error message

**To Reproduce**
0.17 Ver:
pvwatts_kws = {"poa_global" : df.poa,
              "P_ref" : meta['pdc'],
              "T_cell" : df.Tcell,
              "G_ref" : 1000,
              "T_ref": 25,
              "gamma_pdc" : meta['tempco']}
normalized, insolation = rdtools.normalize_with_pvwatts(df.energy, pvwatts_kws)
#----------------------------
0.18 Ver:
pvwatts_kws = {"poa_global" : df.poa,
                "power_dc_rated": meta['pdc'],
               "poa_global_ref":1000, 
               "temperature_cell_ref":25,
              "temperature_cell" : df.Tcell,
              "gamma_pdc" : meta['tempco']}
normalized, insolation = rdtools.normalize_with_pvwatts(df.energy, pvwatts_kws)

**Expected behavior**
should be the same result
**Screenshots**
0.17 Ver:
![image](https://user-images.githubusercontent.com/44451237/107489652-d9b14400-6bc3-11eb-85b5-b1245c9883bf.png)
0.18Ver:
![image](https://user-images.githubusercontent.com/44451237/107489710-e9c92380-6bc3-11eb-9a42-78c757098d86.png)

**Additional context**

Thanks for the great work!

**Comment by mdeceglie** [comment]
@luciaxu2010  Thanks for bringing this up. Happy to help get to the bottom of it. I'm not quite clear one exactly which versions are giving the discrepancy. Can you provide the output of the following in the two environments where you are seeing the difference?
```
import rdtools
print(rdtools.__version__)
```

**Comment by luciaxu2010** [comment]
Hi Michael，I got “0+unknown” when I type print(rdtools.__version__) with the newer version (newest Rdtools+python 3.8), and the older one should be before 2018.dec. Unfortunately I could not look into the older enviroments because I'm looking at the saved jupyter notebook from another computer..

**Comment by mdeceglie** [comment]
Thank you that information is very helpful. In December 2018, the current version was 1.2.2. Version 2.0.0 was released Oct, 2020. Version 2.0.0 (and subsequent releases) did in fact incorporate a change to the normalization calculations. You can read more about the details in the [change log](https://rdtools.readthedocs.io/en/stable/changelog.html#v2-0-0-october-20-2020) and #105 and #108 

We recommend the improved calculations used in version 2+, but you can always install an older version from [pypi](https://pypi.org/project/rdtools/#history) if you need to reproduce something exactly.

Does this address your issue?

**Comment by luciaxu2010** [comment]
Yes, it helped!
The result by new version rdtools.normalize_with_pvwatts  statistically outputs slightly lower degradation than before, too. 

Thanks!

**Comment by mdeceglie** [comment]
Great, glad to hear that the information was helpful. I will go ahead and close this. Thanks!
