### ISSUE TITLE
pandas.core.datetools deprecated

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#27]
importing rdtools gives the following warning: " FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools"

**Comment by yjy1663** [comment]
Cause by `import statsmodels.api as sm` this is fixed by statsmodels upcoming 0.9 release

**Comment by guptaabha** [comment]
how can solve now. please suggest me.

**Comment by mdeceglie** [comment]
Examples are now designed to be run in specified environments (`requirements.txt` + `docs/notebook_requirements.txt`) and we no longer encounter this issue. But if anyone is still having challenges with this, please let us know.
