### ISSUE TITLE
Branch basic_clearsky_workflow utc_offset daylight saving time concern

### ISSUE THREAD

**Issue by yjy1663** [NREL/rdtools#31]
In branch basic_clearsky_workflow degradation_example_clearsky.ipynb
At Australia Alice Springs the utc_offset "TZ" is constant, for locations in US and other daylight saving regions the utc_offset is not constant. 

~~~
meta = {"altitude":0,
        "latitude": -23.762028,
        "longitude": 133.874886,
        "Name": "Alice Springs",
        "State": "n/a",
        "TZ": 9.5,
        "timezone": 'Australia/North',
        "gcr": 0.3,
        "tempco": -0.005,
        "mounting": ['Fixed','Single-Axis'][0],
        "azimuth": 0,
        "tilt": 20,
        "pdc": 5100.0,
        "temp_model": 'open_rack_cell_polymerback'}
~~~

**Comment by GregoryKimball** [comment]
Good point, there is not really a standard when it comes to reporting data with and without daylight savings time.  

I typically use a workflow that removes the daylight savings shifts such that constant `utc_offset` is correct.  Do you think it is appropriate to demonstrate in rdtools the scripts for removing clock shifts/errors?

**Comment by mdeceglie** [comment]
Good catch, timezones are tricky, and I think we can improve. The current meta data contains timezone info twice, once in ` 'timezone' ` and once in `'TZ'`. We should target not having to repeat that information.

I suggest that we should follow the [pvlib example](http://pvlib-python.readthedocs.io/en/latest/timetimezones.html) and use `pytz` and `pandas` functionality for timezone aware `DateTimeIndex`, and avoid placing requirements on how users handle daylight savings time. To do this, I believe we need to update `get_clearsky_tamb` so that it can extract the needed offest from each point in the time series. Here is an example of how that can be achieved.

```
import pandas as pd
import pytz

dates = pd.date_range('2015-01-01', '2015-12-31', freq='1M')
dates = dates.tz_localize('US/Eastern')  # a timezone that obeys DST
offsets = [y.utcoffset().total_seconds()/3600.0 for y in dates]  # calculate the offsets in hours
print offsets # the offset changes in summer/winter

dates = pd.date_range('2015-01-01', '2015-12-31', freq='1M')
dates = dates.tz_localize(pytz.FixedOffset(-5*60))  # a timezone that with a fixed offset
offsets = [y.utcoffset().total_seconds()/3600.0 for y in dates]  # calculate the offsets in hours
print offsets  # the offset is constant throughout the year
```

**Comment by mdeceglie** [comment]
@GregoryKimball or @yjy1663 would one of you like to take charge of this update? We probably don't want you both working on changes to `get_clearsky_tamb` in parallel

**Comment by yjy1663** [comment]
I'm working on get_clearsky_tamb as @mdeceglie suggested, it will have some trade off on our performance.

**Comment by yjy1663** [comment]
Argument 'times' of 'get_clearsky_tamb' was "tz_localize" before passing into the function

adding these three lines give us a new dataframe column 'solar_noon_offset' which later pass into the lambda x as a argument
~~~
utc_offsets = [y.utcoffset().total_seconds()/3600.0 for y in df.index]
solar_noon_offset = lambda utc_offset : longitude / 180.0 * 12.0 - utc_offset
df['solar_noon_offset'] = [solar_noon_offset(utc_offset) for utc_offset in utc_offsets]
~~~

@GregoryKimball and @mdeceglie please help review the code, testing works fine.

**Comment by mdeceglie** [comment]
Thanks @yjy1663, looks good to me! @GregoryKimball, let us know if you have any concerns about the change. Otherwise I think we're good to close the issue.

**Comment by GregoryKimball** [comment]
Thank you @yjy1663 for the great work, and thanks @mdeceglie for your review.  I added a test to confirm the correct handling of timezones.
