### ISSUE TITLE
CODS updates

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#330]
Before a full release of the CODS algorithm (#150) we should address the following:

1. `pd.concat` causes a `FutureWarning` (see notebook example)
2. Rename parameters with `_tuner` in the name
3. Update the CODS example notebook to use PVDAQ4 data
4. Add the CODS example notebook to the CI notebook checks

**Comment by mdeceglie** [comment]
To address item 4, we may need to seed the number random generator

**Comment by kanderso-nrel** [comment]
The progress bar text will also be a problem for item 4:
``` # 16 | Used: 2.2 min | Left: 0.0 min | Progress: [----------------------------->] 100 %```

We could add a new "sanitization" regex in [docs/nbval_sanitization_rules.cfg](https://github.com/NREL/rdtools/blob/master/docs/nbval_sanitization_rules.cfg) to deal with that.  Or just remove the progress bar from the notebook (`verbose=False`).

**Comment by kanderso-nrel** [comment]
I think the docstring description of the `results_dict` returned from `iterative_signal_decomposition` need some tweaks: the `degradation` and `soiling_loss` keys are described as containing lists but the actual return values are scalars.

**Comment by mdeceglie** [comment]
#333 addressed items 1 and 2 here. 3 and 4 should still be addressed before a real release.

**Comment by mdeceglie** [comment]
Items 3 and 4 added in #390
