### ISSUE TITLE
Implement filters

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#34]
Let's use this issue to discuss the development of filters other than clear sky.

**Comment by mdeceglie** [comment]
@amnag Thank you for your work on this issue. Here are comments related to degradation_example_clearsky.ipynb notebook in condition_filter branch:

- I suggest that the interface of all the filters should be the same as that in `csi_filter`. That is, they should take inputs from a time series and return a boolean mask that can be used in the standard pandas filtering syntax eg `df[mask1 & mask2]`

- We talked the other day about eliminating `ConditionFilter` because it can be achieved trivially with pandas filtering. The only value I see would be to provide people with reasonable defaults, but that could be communicated in the examples. What do people think on this issue?

- for `ClipFilter` I suggest that we make the percentile an input variable with a reasonable default e.g. `def ClipFilter(power, quant = 0.95)`

- How confident are we that 0.95 is a good default for clip filter? Would this adversely affect results on a system that has minimal clipping? 

- None of the functions should take entire dataframes as arguments and depend on columns having a particular name. I'd like to avoid this throughout rdtools. Instead functions should the take specific series they work with and return the boolean mask. 

- All names should be lower case with underscores, e.g. `clip_filter` to match the style of the other functions in rdtools.

- I am not yet sold on this version of an outage filter, but could be convinced with examples and data. @GregoryKimball might want to weigh in on this. Perhaps we should do outlier detection based on 1.5 IQR above/below the first and third quantiles? Or something else entirely? Whatever we choose should be backed by validation.

**Comment by mdeceglie** [comment]
Here's a bigger question for everyone: I'd like to avoid having two filtering steps in the workflow if at all possible. Can we formulate filters that would either all be applied before normalization or all after normalization?

**Comment by amnag** [comment]
@mdeceglie, I have addressed most of these comments, please check out the condition_filter branch.

**Comment by mdeceglie** [comment]
We have decided to put filtering after normalization but before aggregation. I have opened issue #37 to improve the normalization functions in support of this.

**Comment by mdeceglie** [comment]
We have also decided to modify the outage filter so that it uses a 30% threshold around the median normalized performance value from the first year of operation. This will be implemented in such a way that an advanced user can use a different method of calculating nominal value.
