### ISSUE TITLE
get_clearsky_tamb is slow

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#35]
This issue is related to the gaussian rolling mean applied to the average day and night temperatures.  This could be sped up by calculating that on a daily index and then upsampling to the full  index.

**Comment by amnag** [comment]
Hi @mdeceglie, @cdeline and @dirkjordan, I just pushed modified and working code to faster_get_clearsky_tamb branch of repository.

**Comment by amnag** [comment]
Hi @mdeceglie, @cdeline and @dirkjordan, there is a speed up by a factor of ~2.4. Please look at the updated docs folder in both the basic_clearsky_workflow and faster_get_clearsky_tamb branches, which now in addition to updated notebooks contains code profiling results using the tools - prun, lprun, time and timeit.

**Comment by mdeceglie** [comment]
@GregoryKimball  - shouldn't the rolling mean in this function be centered?

**Comment by GregoryKimball** [comment]
Yes, I think it should be centered rather than forward or backward.

**Comment by amnag** [comment]
Hi @mdeceglie and @cdeline, I have achieved a further speed-up by a factor of  ~10 by vectorizing the code to the best of by ability. I have pushed a new branch called faster_combined_update to the repo. I created this branch from the combined_update branch. 

However, there is only one issue, even before modifying the code, I am not being able to reproduce the exact numbers in the degradation_example notebook in the combined_update branch. I made sure I am using the latest version of pvlib (0.5.0) and the data file for Site 12 of the Desert Knowledge Australia Solar Centre (downloaded today). I also installed rdtools in the combined_update branch using the "sudo -H pip install . --upgrade" command. May be you can use my rdtools/clearsky_temperature.py code and make sure it works with your copy of the repo ?

**Comment by mdeceglie** [comment]
Great, that speed improvement is awesome! I tested it and was able to reproduce the `combined_update` results. I pushed an update to `combined_update` that explicitly sets the dates for analysis. I wonder if we are working with different versions of the example data and that is causing discrepancy? @amnag , please add the explicit dates into the import step of your testing `df = df['2008-11-11':'2017-05-15']` and see if that allows you to reproduce the results from `combined_update`.

**Comment by mdeceglie** [comment]
Sounds like we're getting the same answers now. I will merge in the faster version, then I will merge the pull request to master.
