### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by jmertic** [NREL/rdtools#363]
Hi! Do you have an SVG version of your logo:

https://github.com/NREL/rdtools/blob/master/docs/sphinx/source/_images/logo_horizontal_highres.png

We would like to include this project in the LF Energy Landscape ( l.lfenergy.org ) and need the high quality SVG to do so. Thanks in advance!

**Comment by jmertic** [comment]
No worries - do you have it in an AI or EPS format perhaps? Those we can convert cleanly.

If not, we can attempt to trace it.

**Comment by mdeceglie** [comment]
Oh we do have an EPS version. I have added a `logos` folder in `docs` you can find them there. The stacked version may be most appropriate for this, but you'll find the horizontal version as well. Thanks for including RdTools in this project!

**Comment by jmertic** [comment]
Awesome - that works perfectly. Thank you!
