### ISSUE TITLE
CODS run_bootstrap can return None

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#367]
When run_bootstrap detects a small soiling signal, it currently returns None (https://github.com/NREL/rdtools/blob/adf9f44c9a65b8955ffb95b3d38b0c29e1760ee3/rdtools/soiling.py#L1769)

Suggested change is `return self.result_df, self.degradation, self.soiling_loss`

**Comment by martin-springer** [comment]
@mdeceglie - I created a pull request to address this issue #400

**Comment by mdeceglie** [comment]
Closed in #400
