### ISSUE TITLE
NonExistentTimeError in rdtools.get_clearsky_tamb

### ISSUE THREAD

**Issue by BernatNicolau** [NREL/rdtools#372]
I have a dataset which has a Daylight Saving Time at 00:00h:

2018-08-11 22:00:00-04:00
2018-08-11 23:00:00-04:00
2018-08-12 01:00:00-03:00
2018-08-12 02:00:00-03:00

When running rdtools.get_clearsky_tamb, this error occurs 
NonExistentTimeError: 2018-08-12 00:00:00

Triggered in line 59 of rdtools/clearsky_temperature.py:

dt_daily = pd.date_range(times.date[0] - buffer, times.date[-1] + buffer, freq='D', tz=times.tz)

**Comment by mdeceglie** [comment]
Thanks for submitting this issue @BernatNicolau. Can you please provide the complete code for a minimal example that reproduces the error?

**Comment by BernatNicolau** [comment]
Hello,

Sure, here it is:


```
import datetime
import pandas as pd
import rdtools

tz = 'America/Santiago'
start_date = datetime.datetime(2018, 1, 1, 0, 0, 0)
end_date = datetime.datetime(2023, 5, 18, 23, 0, 0)
freq ='H'
lat = -24
lon = -70

times = pd.date_range(start=start_date, end=end_date, freq=freq)
df = pd.DataFrame(index=times)

df.index = df.index.tz_localize(tz = tz, ambiguous=True, nonexistent='shift_forward')

tamb = rdtools.get_clearsky_tamb(df.index, lat, lon)
```

I think the problem might be that in rdtools.get_clearsky_tamb, there's not the option to add a nonexistent order. If there is, I'm sorry for the time spent...

**Comment by mdeceglie** [comment]
Thanks, that helps me reproduce the error. It seems the underlying issue is this: https://github.com/pandas-dev/pandas/issues/30378 I think I have a workaround in #373

**Comment by BernatNicolau** [comment]
Thank you very much @mdeceglie !

**Comment by mdeceglie** [comment]
Closed with https://github.com/NREL/rdtools/pull/373 and version 2.1.6
