### ISSUE TITLE
Resampling

### ISSUE THREAD

**Issue by dirkjordan** [NREL/rdtools#39]
The line df=df.resample(freq).asfreq() resamples instantaneous values. For example, at the OTF we used to sample at 15min and in 2010 changed to 1min intervals. The way it is written now most of the data after 2010 are being ignored. For example, the value 12/31/2016 11:45pm is the instantaneous value measured at that time stamp. It ignores the data from 12/31/2016 11:46pm till midnight. I suggest for cleaner data we change the line everywhere to: df=df.resample(freq).median(). I open a new issue because this line occurs in a lot of places in different branches. Incidentally, data loggers typically work the same way, 5s values are collected and being averaged into "1min" data.

**Comment by amnag** [comment]
Done !
