### ISSUE TITLE
Clarification on "gamma_pdc"

### ISSUE THREAD

**Issue by froggy555** [NREL/rdtools#403]
What does gamma_pdc mean? And how did you determine that this value must be between -0.002 to -0.005?

<img width="376" alt="image" src="https://github.com/NREL/rdtools/assets/153564119/ff7c02fe-4afb-49dc-9a80-e898686ac517">

**Comment by dirkjordan** [comment]
gamma_pdc is the maximum power temperature coefficient. It is commonly found on module datasheets and is denoted by the Greek letter gamma. Values range typically from around -0.2%/Celsius (thin-film modules) to -0.5%/Celsius (very, very old crystalline silicon modules). Express the %/C as absolute number and one obtains the above range (-0.002)-(-0.005).

**Comment by froggy555** [comment]
> gamma_pdc is the maximum power temperature coefficient. It is commonly found on module datasheets and is denoted by the Greek letter gamma. Values range typically from around -0.2%/Celsius (thin-film modules) to -0.5%/Celsius (very, very old crystalline silicon modules). Express the %/C as absolute number and one obtains the above range (-0.002)-(-0.005).

I see, but what does the gamma refer to ?

**Comment by cwhanse** [comment]
Traditionally, temperature coefficients for current are named alpha, and temperature coefficients for voltage are named beta. I suppose that's where gamma for power originates (third letter of Greek alphabet).

**Comment by mdeceglie** [comment]
Thanks for the question @froggy555 and for the responses @cwhanse and @dirkjordan . I'm going to go ahead and close the issue, but let us know if we can clarify anything.
