### ISSUE TITLE
What to do if I don't have expected power?

### ISSUE THREAD

**Issue by matsuobasho** [NREL/rdtools#409]
**Is your feature request related to a problem? Please describe.**
I'm not sure if I'm missing something in the documentation or if this hasn't really been considered.

**Describe the solution you'd like**
I have plant data where the temperature measurements are unreliable and I don't have independent weather station data - so I don't have data for expected power, which is necessary to proceed with availability analysis.  

**Describe alternatives you've considered**
Tried to look for whether there's an rdtools google group similar to one for pvlib, but haven't found it.

**Additional context**
Refer to the docstring of the `AvailabilityAnalysis` class: https://github.com/NREL/rdtools/blob/master/rdtools/availability.py#L59C1-L66C17

**Comment by mdeceglie** [comment]
Thanks for reaching out @matsuobasho. One option may be to generate expected power based on satellite weather data (e.g. https://nsrdb.nrel.gov/data-viewer ). @kandersolar do you have insights into using satellite data (or other alternatives) for the availability analyses?

**Comment by kandersolar** [comment]
Sure, satellite data works.  The expected energy is used to estimate loss during times when the whole system is offline, which often means that the on-site weather monitoring instrumentation is offline too, so satellite data is often the only reasonable option.  The availability analysis in the PV Fleets program used NSRDB data for the expected energy.  The method's [reference](https://www.nrel.gov/docs/fy20osti/76022.pdf) says this too:

> During a site wide communications outage, the expected production is calculated using satellite weather data or nearby weather station measurements if they're available.

**Comment by matsuobasho** [comment]
Great, thanks @kandersolar and @mdeceglie
