### ISSUE TITLE
Add automatic clearsky scaling

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#41]
When the irradiance from the clear sky model and a ground based sensor are offset from one another, it is necessary to rescale the clear sky model for the purposes of detection. This issue is for the development of a function to automatically perform this scaling.

**Comment by GregoryKimball** [comment]
Sensor and modeled clear sky irradiance should be close, at least as close as 50% of the clear sky filtering window.  So for a 20% clear sky index filter, I would recommend the sensor and modeled clear sky irradiance to correspond within 10%.  

For bigger offsets, here is a code sample I have used to scale the sensor irradiance.  

`           df_filtered = df[df['Irradiance POA (W/m2)']>200]
            median_clear_sky = df_filtered['Clear Sky Index'].median()
            deviation = abs(median_clear_sky-1.0)
            if deviation > 0.05 and deviation < 0.5:
                df['Irradiance POA (W/m2)'] = df['Irradiance POA (W/m2)'] / median_clear_sky
                df['Clear Sky Index'] = df['Irradiance POA (W/m2)'] / df['Clear Sky Irradiance (W/m2)']
                print 'normalizing irradiance, ', median_clear_sky
`

**Comment by mdeceglie** [comment]
The following seems to work pretty well, even for big offsets. I plan to include it in a combined update pull request in the near future. 

```
from scipy.optimize import minimize

def irradiance_rescale(irrad, modeled_irrad):
    def _rmse(fact):
        rescaled_modeled_irrad = fact * modeled_irrad
        csi = irrad / rescaled_modeled_irrad
        filt = (csi >= 0.8) & (csi <= 1.2)
        rmse = np.sqrt(((rescaled_modeled_irrad[filt] - irrad[filt]) ** 2.0).mean())
        return rmse
    
    guess = np.percentile(irrad.dropna(), 90) / np.percentile(modeled_irrad.dropna(), 90)
    min_result = minimize(_rmse, guess, method = 'Nelder-Mead')
    factor = min_result['x'][0]
    
    out_irrad = factor * modeled_irrad
    return out_irrad
```
