### ISSUE TITLE
pypi deploy is broken

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#416]
https://github.com/NREL/rdtools/actions/runs/9330988081/job/25685152779#step:5:158

**Comment by martin-springer** [comment]
We might want to upgrade to trusted publishing: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

We've done that for pvdeg: https://github.com/NREL/PVDegradationTools/blob/main/.github/workflows/publish-to-pypi.yml

This requires to add the github workflow to the trusted publisher management on pypi. I don't have access to rdtools on pypi. Those settings can be found under the repo -> "Manage" -> "Publishing"

![image](https://github.com/NREL/rdtools/assets/97482055/8099fa98-a90e-4cec-b65a-7a3e1df2241e)

**Comment by martin-springer** [comment]
resolved with #427
