### ISSUE TITLE
1-axis tracker clear-sky

### ISSUE THREAD

**Issue by dirkjordan** [NREL/rdtools#42]
The clear-sky modeling for a 1-axis tracker is incorrect. Currently, we model it the same way as a fixed tilt, which leads to erroneous filtering on clear days. I have been talking to Sandia about it and there should be a way using pvlib 0.5.0. I haven't figured out exactly how but as a reminder to myself and everybody involved I'm opening a new issue. I think we may not have to have it worked out for our first release but we should eventually resolve it.

**Comment by mdeceglie** [comment]
This is a somewhat old issue, we've now clearly defined modeling (including SAT transposition) outside the scope of RdTools.
