### ISSUE TITLE
Include functionality to handle problematic timestamps and clock errors

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#44]

**Comment by cdeline** [comment]
This should be a high priority.  From our analyst intercomparison, the majority of differences between analyst has to do with incorrect timestamps, and incorrect application of daylight saving time  shift.

**Comment by mdeceglie** [comment]
To start, it would be helpful to generate a specific list of the problems we would like to help users avoid. 
Two on my list are:
1. Time zone of pandas index is completely wrong, doesn't point to the correct moment (e.g. UTC time) of the measurement
2.  Time zone is geographically correct but DST is not handled the same was as it was by the logger/DAQ

We should consider requiring timezone aware pandas indices (or at least raising a warning).

**Comment by wholmgren** [comment]
I'd be interested in seeing your solution incorporated into pvlib's new `iotools` subpackage. Happy to collaborate on this if you're interested. Also would be useful for our new Solar Forecasting 2 project. cc @cwhanse

**Comment by wholmgren** [comment]
I should add that if you guys are in a rush or just want to retain more control over your workflow then keeping it within rdtools makes sense too.

**Comment by mikofski** [comment]
I wonder if any of the timeseries qc tests/filters tools from [Pecos](https://pecos.readthedocs.io/en/latest/qc_tests.html) could be useful? sorry, if irrelevant. cc @kaklise

**Comment by kaklise** [comment]
That sounds interesting, let me know if you want to collaborate on that.

Kate

**Comment by mdeceglie** [comment]
@wholmgren and @kaklise we'd be happy to work together. Perhaps once the solution takes shape we can figure out which package would be the best home to make sure it reaches its audience and contributes to a well-thought-out ecosystem for PV analysis and modeling.

Step 0 is to come up with some examples of the problems we're trying to solve, we'll work on that.

(thanks for the suggestion @mikofski, not irrelevant!)

**Comment by mdeceglie** [comment]
This kind of QA functionality may be a better fit for https://github.com/pvlib/pvanalytics (which didn't exist when we first considered it)
