### ISSUE TITLE
Add python 3 support

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#56]

**Comment by jimjosephjohn** [comment]
Is python 3 support done?.

**Comment by mdeceglie** [comment]
Nope, this is still on the to do list. If you should take it on, once your changes are ready for review, please open a pull request to the `development` branch. Thanks for your interest and support!

**Comment by jimjosephjohn** [comment]
I am still getting used to the tool.

Great work.

**Comment by mikofski** [comment]
I will help with this

**Comment by mikofski** [comment]
@mdeceglie I think this is good to go, can you think of any more tests to try? maybe set it shake it around a bit to see what falls out first?

**Comment by mdeceglie** [comment]
@mikofski, awesome, thanks for your help on this issue! I'll take a look in the coming week.

**Comment by mdeceglie** [comment]
Fixed in development with PR #72
