### ISSUE TITLE
Problem with get_clearsky_tamb function in rdtools/clearsky_temperature.py

### ISSUE THREAD

**Issue by amnag** [NREL/rdtools#57]
The get_clearsky_tamb function in rdtools/rdtools/clearsky_temperature.py still fails to work unless the line:

freq_actual = pd.infer_freq(times) 

is changed to to

freq_actual = pd.infer_freq(times) if pd.infer_freq(times) != None else pd.infer_freq(times[:10])

or to 

freq_actual = times.freqstr

Please see new rdtools branch fix_freq_inference

**Comment by mdeceglie** [comment]
@amnag please take a look at my proposed solution in the branch `issue_57` and let me know what you think. (The branch `fix_freq_inference` appeared to have unrelated changes to the notebooks, so I started a new branch.)

**Comment by mdeceglie** [comment]
This has been addressed in pull request #61 to `development`. We can close this once it it is merged to master in the next release.
