### ISSUE TITLE
Automate Deployment using TravisCI

### ISSUE THREAD

**Issue by abshinn** [NREL/rdtools#85]
Suggested by @mikofski -- now that TravisCI is set up for automatic testing, it would be easy to set up automatic releases to PyPi (pip source) using TravisCI.

**A few considerations before we automate releases:**

- The [current release procedure](https://github.com/NREL/rdtools/wiki/Release-procedure) involves manually running the example notebook to ensure that it still works with new dependencies or code changes. We may be able to automate this task by saving the notebook to a python script (using [nbconvert](https://nbconvert.readthedocs.io/)) and running this script on TravisCI as a separate build. The notebook requires test data from Alice Springs, which would be inefficient to download in a build every time. We can get around this problem by [caching the test data](https://docs.travis-ci.com/user/caching/#caching-directories-bundler-dependencies) (or perhaps a pared-down subset of the data).
- If RdTools users build their environments with Conda, we should consider testing in the Conda environment and [releasing to the Conda package manager](https://conda.io/docs/user-guide/tasks/build-packages/index.html). 
- If we do not want to release a new version to PyPi on every change to the master branch, we can [trigger releases with git tags](https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags).

**Automatic deployment requires just a few additional lines to .travis.yml:**

```
deploy:
  provider: pypi
  user: "Your username"
    secure: "Your encrypted password"
on:
  branch: master
```

Note from @mikofski on using a hidden environment variable in place of "secure" above:

> please don't commit any personal secrets to your github repo, so you could use the travis CLI to generate a secure key, or use the travis settings page online to set a hidden environment variable, eg: $PYPI_PASSWORD, which you then use in your .travis.yml, you can use sunpower/pvmismatch/.travis.yml or breakingbytes/simkit/.travis.yml as examples

**Comment by mdeceglie** [comment]
I support the idea of automated deployment only on master and only on tagged commits. Until we get some automated test of the examples and full workflow, I'd also support keeping the manual notebook check before we merge `development` into `master` and tag a release.
