### ISSUE TITLE
Document environment for running example notebook

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#86]
The example jupyter notebook requires more packages (e.g. `matplotlib`) to run than RdTools library itself. It would be helpful to generate a `notebook_requirements.txt` file that users can use to set up an environment ensuring the example notebook runs smoothly.

**Comment by abshinn** [comment]
This file was added in PR #82, in the docs dir:
https://github.com/NREL/rdtools/blob/development/docs/notebook_requirements.txt

I tested to make sure the notebook ran to completion using this set of requirements. Of course, some of these requirements may differ slightly in other environments.

**Comment by mdeceglie** [comment]
Oops sorry I missed that. Let's leave this open until it gets pushed to master.

**Comment by wholmgren** [comment]
This line requires ``pytables``, which is an optional dependency for pvlib and thus not included in the standard pvlib installation:

```
clearsky = loc.get_clearsky(df.index, solar_position = sun)
```

I suggest using a fixed ``linke_turbidity`` or adding a comment about the need to manually install pytables if the cell execution fails.

**Comment by wholmgren** [comment]
Forgot to add... see pvlib/pvlib-python#553 for context.
